### ISSUE TITLE
Config.json file not found that will have slaves information

### ISSUE THREAD

**Issue by abhi041980** [aesteve/vertx-load-balancer#3]

**Comment by abhi041980** [comment]
@aesteve : apart from this Pump.pump(response, proxyResponse) not working.... here response is not a ReadStream... can I have the correct stream code please?

**Comment by aesteve** [comment]
See #2 .

Response is not a ReadStream because in Vert.x 3.2 (8 years ago) it was not.

**Comment by aesteve** [comment]
If you're looking for an equivalent of Pump.pump in newer Vert.x versions in the context of HTTP requests / responses, give: https://vertx.io/docs/vertx-http-proxy/java/ a look.

You may want to use this directly, or look at its implementation:  https://github.com/eclipse-vertx/vertx-http-proxy/
